# Generated by Django 3.2.16 on 2022-12-07 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('telegram', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('skills', models.TextField(default=' ')),
                ('languages', models.TextField(default=' ')),
                ('study', models.TextField(default=' ')),
                ('job_experience', models.TextField(default=' ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
